repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: [--maxkb=1024]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        name: ruff (linter & import sorter)
        args: [--fix, --exit-non-zero-on-fix, --ignore=F811]
    -   id: ruff-format
        name: ruff (formatter)

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        name: ruff (linter)
        args: [--fix, --exit-non-zero-on-fix, --ignore=F811]
    -   id: ruff-format
        name: ruff (formatter)

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false