"""Add has_seen_tutorial to User model

Revision ID: 5bd4570dcfe6
Revises: 73ea76b0f2e3
Create Date: 2025-08-07 22:44:14.430078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd4570dcfe6'
down_revision = '73ea76b0f2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seen_tutorial', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_seen_tutorial')

    # ### end Alembic commands ###
